services:
  postgres:
    build:
      context: ../docker/postgres
      dockerfile: Dockerfile
    image: quantumpacs-postgres:16
    container_name: quantumpacs-postgres-1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quantumpacs
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: quantumpacs
    volumes:
      - quantumpacs_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantumpacs"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  quantumpacs_pgdata:
